name: フィーチャー ブランチを push した際のアクション
on:
  push:
    branches:
      - "*"
      - "!main"
jobs:
  build:
    name: ソースコードの検証
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトします。
        uses: actions/checkout@v2
