concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
name: The CI workflow on push
on:
  push:
permissions:
  contents: read
run-name: Pushed by @${{ github.actor }}
jobs:
  build:
    name: lint + typecheck + test
    runs-on: ubuntu-latest
    steps:
      - name: Stages the pushed branch
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup the pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Prepare the Node.js 24 (Krypton) environment
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          check-latest: true
          node-version: 24.x
      - env:
          HUSKY: 0
        name: Install the dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Lint
        run: pnpm run lint
      - name: Typecheck
        run: pnpm run typecheck
      - name: Test
        run: pnpm run test
    timeout-minutes: 10
